// DOM element references
const grid = document.getElementById('grid');
const gridExploration = document.getElementById('grid-exploration');
const shuffleBtn = document.getElementById('shuffle-btn');
const solveBtn = document.getElementById('solve-btn');
const replayBtn = document.getElementById('replay-btn');
const algorithmSelect = document.getElementById('algorithm-select');
const statusDiv = document.getElementById('status');
const statsContainer = document.getElementById('stats-container');
const statNodes = document.getElementById('stat-nodes');
const statTime = document.getElementById('stat-time');
const statPath = document.getElementById('stat-path');
const pauseBtn = document.getElementById('pause-btn');
const skipBtn = document.getElementById('skip-btn');
const speedSelect = document.getElementById('speed-select');
const modal = document.getElementById('node-modal');
const modalClose = document.querySelector('.modal-close');
const zoomInBtn = document.getElementById('zoom-in-btn');
const zoomOutBtn = document.getElementById('zoom-out-btn');
const resetZoomBtn = document.getElementById('reset-zoom-btn');
const toggleGridBtn = document.getElementById('toggle-grid-btn');
const fullscreenBtn = document.getElementById('fullscreen-btn');
const treeSection = document.querySelector('.tree-section');

// Solution Controls
const solPrevBtn = document.getElementById('sol-prev-btn');
const solPlayBtn = document.getElementById('sol-play-btn');
const solNextBtn = document.getElementById('sol-next-btn');
const solStepDisplay = document.getElementById('sol-step-display');
